/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_AD_28 (coord L17), LPSPI1_SCK/U27[6]/BT_DEV_WAKE/U354[9]/U16[39]/J10[12] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_AD_31 (coord J17), LPSPI1_SDI/U27[2]/J10[10] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDI_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDI_SIGNAL                                     SIN   /*!< Signal name */

/* GPIO_AD_30 (coord K17), LPSPI1_SDO/U27[5]/J10[8]/Backlight_CTL/J48[34]/U46[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDO_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDO_SIGNAL                                    SOUT   /*!< Signal name */

/* GPIO_AD_29 (coord M17), LPSPI1_PCS0/U27[1]/J10[6]/WL_HOST_WAKE/U16[27]/WIFI_WAKE_B_3V3/U355[21] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS0_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS0_SIGNAL                                   PCS0   /*!< Signal name */

/* GPIO_AD_18 (coord M16), SAI1_RX_SYNC/J9[5]/J50[19]/U32[13] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS1_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS1_SIGNAL                                   PCS1   /*!< Signal name */

/* GPIO_AD_19 (coord L16), SAI1_RX_BCLK/J9[1]/J50[18]/U32[12] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS2_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS2_SIGNAL                                   PCS2   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
